version: "3"
services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - TZ=America/New_York
      - IFACE=ovs_bond0                  # required: 1 or more interface
      - DBPATH=/data/db.sqlite         # optional, default: /data/db.sqlite
      - GUIPORT=8840                   # optional, default: 8840
      - TIMEOUT=120                    # optional, time in seconds, default: 60
#      SHOUTRRR_URL: ""                  # optional, set url to notify
      - THEME=darkly                   # optional
